name: dreamzoneapp
description: "DZI Infinity - All Digital Services in One Place"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  email_validator: ^3.0.0
  url_launcher: ^6.3.2
  file_picker: ^8.1.2
  video_player: ^2.8.2
  shared_preferences: ^2.5.5
  path_provider: ^2.1.6
  open_filex: ^4.7.0
  razorpay_flutter: ^1.4.5
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
